# language_pack.py
lang_pack = {
    "繁體中文": {
        "title": "卡式如通訊品質監測平台",
        "team_name": "卡式如研發團隊",
        "control_center": "控制中心",
        "speed_test": "即時效能測試",
        "sla_mode": "監測場景 (SLA Mode)",
        "audit_hash": "稽核編號",
        "node": "監測節點",
        "m1": "全球監測單元",
        "m2": "即時延遲 (RTT)",
        "m3": "網路抖動 (Jitter)",
        "m4": "SLA 達標率",
        "diag_title": "鏈路效能時域分析",
        "map_title": "全球節點拓撲",
        "list_title": "系統監測動態清單",
        "export_btn": "導出專業監測報告 (CSV)",
        "unit_name": "單位名稱",
        "location": "地理位置",
        "last_seen": "最後活動紀錄",
        "speed_btn": "開始測速",
        "speed_wait": "等待指令...",
        "speed_testing": "測試中...",
        "modes": ["一般辦公", "即時競技", "遠距會議", "影音串流"],
        # 新增登入系統欄位
        "login_section": "帳號存取系統",
        "tab_login": "登入",
        "tab_register": "註冊",
        "user_label": "帳號",
        "pass_label": "密碼",
        "btn_signin": "立即登入",
        "btn_signup": "建立帳號",
        "auth_welcome": "歡迎回來",
        "auth_role": "權限等級",
        "auth_logout": "登出系統",
        "db_title": "DataBase: 全系統即時狀態",
        "user_record": "個人監測紀錄",
        "lock_msg": "🔒 請登入以啟動網路監測與數據儲存。",
        "err_auth": "帳號或密碼錯誤",
        "err_exists": "帳號已存在",
        "reg_success": "註冊成功，請登入",
        "version_info": "開發版 V0.1",
        "team_name": "卡式如通訊團隊",
    },
    "English": {
        "title": "KSR Network Telemetry Platform",
        "team_name": "KSR R&D Team",
        "control_center": "CONTROL CENTER",
        "speed_test": "THROUGHPUT TEST",
        "sla_mode": "SLA Profile Selection",
        "audit_hash": "Audit Hash",
        "node": "Active Node",
        "m1": "Monitoring Units",
        "m2": "RTT Latency",
        "m3": "Network Jitter",
        "m4": "SLA Compliance",
        "diag_title": "Time-Domain Performance Analysis",
        "map_title": "Global Topology Map",
        "list_title": "Active Node Registry",
        "export_btn": "Export Audit Report (CSV)",
        "unit_name": "Unit Identifier",
        "location": "Geolocation",
        "last_seen": "Last Heartbeat",
        "speed_btn": "RUN SPEED TEST",
        "speed_wait": "STANDBY",
        "speed_testing": "TESTING...",
        "modes": ["Standard", "Gaming", "VoIP", "Streaming"],
        # New Login fields
        "login_section": "Account Access System",
        "tab_login": "Login",
        "tab_register": "Register",
        "user_label": "Username",
        "pass_label": "Password",
        "btn_signin": "Sign In",
        "btn_signup": "Sign Up",
        "auth_welcome": "Welcome back",
        "auth_role": "Role",
        "auth_logout": "Logout",
        "db_title": "DataBase: Global Real-time Status",
        "user_record": "Personal Monitoring Record",
        "lock_msg": "🔒 Please login to enable telemetry and data logging.",
        "err_auth": "Invalid username or password",
        "err_exists": "Username already exists",
        "reg_success": "Registration successful!",
        "version_info": "Development Build V0.1",
        "team_name": "KSR Network Team"
    }
}
